# --- SERVER ---
quarkus.http.host=0.0.0.0
quarkus.http.port=${PORT:8080}  # Render imposta la porta tramite variabile d'ambiente


# --- DATABASE (Neon PostgreSQL) ---
# PostgreSQL Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=neondb_owner
quarkus.datasource.password=npg_1xqrofsPVZ2E
quarkus.datasource.jdbc.url=jdbc:postgresql://ep-blue-hat-abs1hipi-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
quarkus.hibernate-orm.packages=com.mvpiq.model
quarkus.hibernate-orm.database.generation=none

quarkus.datasource.jdbc.min-size=2
quarkus.datasource.jdbc.max-size=20

# --- HIBERNATE / JPA ---
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=no-file

# --- VIDEO / MEDIA STORAGE ---
# Se usi Cloudflare R2 compatibile S3:
quarkus.s3.endpoint=${S3_ENDPOINT}     # es. https://<account>.r2.cloudflarestorage.com
quarkus.s3.access-key=${S3_ACCESS_KEY}
quarkus.s3.secret-key=${S3_SECRET_KEY}
quarkus.s3.bucket=${S3_BUCKET_NAME}

# --- LOGGING ---
quarkus.log.console.level=INFO
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n


