#App Config
quarkus.http.host=0.0.0.0
quarkus.http.port=8080
url.root.spid=http://localhost:4200/mvpiq

#App Info
quarkus.application.name=MVPiQ
quarkus.application.ui-header={applicationName} by MVPiQ | powered by Quarkus
quarkus.application.version=1.0.0
quarkus.banner.path=banner.txt
quarkus.cache.caffeine.tokenCache.expire-after-access=3000S
quarkus.tls.trust-all=true
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,PUT,POST,DELETE

# PostgreSQL Datasource
# quarkus.datasource.db-kind=postgresql
# quarkus.datasource.username=owner
# quarkus.datasource.password=mnXkEJCSWWzwHchSE6bs8PQY53tj51J0
# quarkus.datasource.jdbc.url=jdbc:postgresql://dpg-d4s6kh6uk2gs73a6gv00-a.frankfurt-postgres.render.com/mvpiq
# quarkus.hibernate-orm.packages=com.mvpiq.model
# quarkus.hibernate-orm.database.generation=validate

quarkus.hibernate-orm.mapping.format.global=ignore
quarkus.datasource.devservices.enabled=false

# --- DATABASE (Neon PostgreSQL) ---
# PostgreSQL Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=neondb_owner
quarkus.datasource.password=npg_1xqrofsPVZ2E
quarkus.datasource.jdbc.url=jdbc:postgresql://ep-blue-hat-abs1hipi-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
quarkus.hibernate-orm.packages=com.mvpiq.model
quarkus.hibernate-orm.schema-management.strategy=validate

# JWT
mp.jwt.verify.issuer=mvpiq-hoops
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem

supabase.url=https://gnjwgcronnnzxokmuqlw.supabase.co
supabase.service.key=sb_publishable_HSN01laxzF6TY_aqkbCRbA_Gql47mXa
supabase.bucket.videos=videos
supabase.bucket.frames=analysis-frames

