#App Config
quarkus.http.port=8081
url.root.spid=http://localhost:4200/mvpiq

#App Info
quarkus.application.name=MVPiQ
quarkus.application.ui-header={applicationName} by MVPiQ | powered by Quarkus
quarkus.application.version=1.0.0
quarkus.banner.path=banner.txt
quarkus.cache.caffeine.tokenCache.expire-after-access=3000S
quarkus.tls.trust-all=true
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,PUT,POST,DELETE

# PostgreSQL Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=neondb_owner
quarkus.datasource.password=npg_1xqrofsPVZ2E
quarkus.datasource.jdbc.url=jdbc:postgresql://ep-blue-hat-abs1hipi-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
quarkus.hibernate-orm.packages=com.mvpiq.model
quarkus.hibernate-orm.database.generation=validate

